% B.Shyrokau
% Template for homework assignment #3
% RO47017 Vehicle Dynamics & Control
% Use and distribution of this material outside the RO47017 course 
% only with the permission of the course coordinator

clc; clear all; close all; clear mex;

% controller settings
Ts = 0.01;	% controller frequency

% vehicle parameters (bicycle model)
veh_parameters;

%% ACADO set up 
DifferentialState vx yaw Xp Yp; % definition of controller states
Control delta; % definition of controller input
% controller model of the plant
beta = atan(par.l_r * tan (delta) / par.L);

f_ctrl = [
    dot(vx)  == 0;...
    dot(yaw) == vx / par.l_r * sin(beta);...
    dot(Xp)  == vx * cos(yaw + beta);...
    dot(Yp)  == vx * sin(yaw + beta)];

%% ACADO: controller formulation
acadoSet('problemname', 'PF_problem');
Np = 40;                                  % prediction horizon
ocp  = acado.OCP( 0.0, Np*Ts, Np);        % ACADO ocp

% Residual function definition based on ACADO
h = [diffStates ; controls];
hN = [diffStates];                       % terminal

% Initialization weights
W = acado.BMatrix(eye(length(h)));
WN = acado.BMatrix(eye(length(hN)));     % terminal

% Cost definition
ocp.minimizeLSQ(W,h);
ocp.minimizeLSQEndTerm(WN,hN);           % terminal

% Constraints definition
beta_thd       = 10 / 180*pi;            % absolute sideslip 
delta_thd   = 360/180*pi / par.i_steer;	 % absolute steering position

% constraints in ACADO 
ocp.subjectTo( -delta_thd   <= delta    <= delta_thd);
ocp.subjectTo( -beta_thd   <= beta    <= beta_thd);

% define ACADO prediction model
ocp.setModel(f_ctrl);
    
% ACADO settings [Don't change these settings in your HMA]
mpc = acado.OCPexport( ocp );
mpc.set('HESSIAN_APPROXIMATION', 'GAUSS_NEWTON');       % solving algorithm
mpc.set('DISCRETIZATION_TYPE', 'MULTIPLE_SHOOTING');    % discretization algorithm
mpc.set('INTEGRATOR_TYPE', 'INT_IRK_GL2');              % intergation algorithm
mpc.set('NUM_INTEGRATOR_STEPS', 3*Np);                  % number of integration steps
mpc.set('LEVENBERG_MARQUARDT', 1e-4);                   % value for Levenberg-Marquardt regularization -> affects performance
mpc.set('SPARSE_QP_SOLUTION', 'FULL_CONDENSING_N2');
mpc.set('QP_SOLVER', 'QP_QPOASES3');
mpc.set('MAX_NUM_QP_ITERATIONS', 20) ;
mpc.set('HOTSTART_QP','YES');
mpc.set('GENERATE_SIMULINK_INTERFACE', 'YES');

%% Export and Compile flags
EXPORT  = 1;
COMPILE = 1;

% export code to the defined folder
if EXPORT
    mpc.exportCode('export_MPC');
end

% compilation of the S-function using autogenerated make script
if COMPILE
    global ACADO_;
    copyfile([ACADO_.pwd '/../../external_packages/qpoases3'], 'export_MPC/qpoases3')
    cd export_MPC
    make_acado_solver_sfunction
    copyfile('acado_solver_sfun.mex*', '../')
    cd ..
end

%% initial MPC settings
disp('Initialization')
X0       = [V_ref 0 0 0];             % initial state conditions
% initialize controller bus
input.x  = repmat(X0, Np + 1, 1).';      % size Np + 1
input.od = zeros(Np + 1, 1);            % size Np + 1
Uref     = zeros(Np, 1);
input.u  = Uref.';
input.y  = [repmat(X0, Np, 1) Uref].';   % reference trajectory, size Np + 1
input.yN = X0.';                        % terminal reference, size Np + 1
% redefined in Simulink
input.W  = diag([0 0 0 5e-3 1e-1]);     % weight tuning !! Tune them in the Simulink model !!
input.WN = diag([0 0 0 0]);             % terminal weight tuning
input.x0 = X0.';
% controller bus initialization
init.x   = input.x(:).';                  % state trajectory
init.u   = input.u(:).';                  % control trajectory
init.y   = input.y(:).';                  % reference trajectory (up to Np - 1)
init.yN  = input.yN(:).';                % terminal reference value (only for Np)
init.W   = input.W(:).';                  % stage cost matrix (up to Np - 1)
init.WN  = input.WN(:).';                % terminal cost matrix (only for Np)
init.x0  = input.x0(:).';                % initial state value


%% Caculate RMSE

% ts_actual = simout1;
% ts_predicted = simout;
% 
% % Convert timeseries to arrays
% actual = ts_actual.Data;
% predicted = ts_predicted.Data;
% 
% % Calculate RMSE
% difference = actual - predicted;
% squaredErrors = difference .^ 2;
% meanSquaredError = mean(squaredErrors);
% rmse = sqrt(meanSquaredError);
% 
% disp(rmse);


%% Plots for comparison

% figure()
% plot(simout,'r')
% hold on
% plot(simout1,'--')
% hold on
% plot(simout2,':')
% hold on
% plot(simout3,'-.')
% hold on
% plot(simout4,'-')
% hold on
% plot(simout5,'--')
% legend('y reference','y1 when Q(4,4)=0.005','y2 when Q(4,4)=0.01','y3 when Q(4,4)=0.02','y4 when Q(4,4)=0.03','y5 when Q(4,4)=0.04')
% xlabel('Simulation time [s]')
% ylabel('y [m]')
% title('Lateral position')
% 
% 
% 
% figure()
% plot(w1,'--')
% hold on
% plot(w2,':')
% hold on
% plot(w3,'-.')
% hold on
% plot(w4,'-')
% hold on
% plot(w5,'--')
% legend('y1 when Q(4,4)=0.005','y2 when Q(4,4)=0.01','y3 when Q(4,4)=0.02','y4 when Q(4,4)=0.03','y5 when Q(4,4)=0.04')
% xlabel('Simulation time [s]')
% ylabel('delta [rad]')
% title('Steer Wheel Angle')
% 
% figure()
% plot(simout,'r')
% hold on
% plot(simout1,'--')
% hold on
% plot(simout2,':')
% hold on
% plot(simout3,'-.')
% hold on
% plot(simout4,'-')
% hold on
% plot(simout5,'--')
% legend('y reference','y1 when Q(4,4)=0.005','y2 when Q(4,4)=0.002','y3 when Q(4,4)=0.001','y4 when Q(4,4)=0.0005','y5 when Q(4,4)=0.0002')
% xlabel('Simulation time [s]')
% ylabel('y [m]')
% title('Lateral position')
% 
% 
% 
% figure()
% plot(w1,'--')
% hold on
% plot(w2,':')
% hold on
% plot(w3,'-.')
% hold on
% plot(w4,'-')
% hold on
% plot(w5,'--')
% legend('y1 when Q(4,4)=0.005','y2 when Q(4,4)=0.002','y3 when Q(4,4)=0.001','y4 when Q(4,4)=0.0005','y5 when Q(4,4)=0.0002')
% xlabel('Simulation time [s]')
% ylabel('delta [rad]')
% title('Steer Wheel Angle')
% 
% figure()
% plot(simout,'r')
% hold on
% plot(simout1,'--')
% hold on
% plot(simout2,':')
% hold on
% plot(simout3,'-.')
% hold on
% plot(simout4,'-')
% legend('y reference','y1 when R=0.1','y2 when R=0.05','y3 when R=0.02','y4 when R=0.01')
% xlabel('Simulation time [s]')
% ylabel('y [m]')
% title('Lateral position')
% 
% 
% 
% figure()
% plot(w1,'--')
% hold on
% plot(w2,':')
% hold on
% plot(w3,'-.')
% hold on
% plot(w4,'-')
% legend('y1 when R=0.1','y2 when R=0.05','y3 when R=0.02','y4 when R=0.01')
% xlabel('Simulation time [s]')
% ylabel('delta [rad]')
% title('Steer Wheel Angle')
% 
% figure()
% plot(simout,'r')
% hold on
% plot(simout1,'--')
% hold on
% plot(simout2,':')
% hold on
% plot(simout3,'-.')
% hold on
% plot(simout4,'-')
% hold on
% plot(simout5,'--')
% legend('y reference','y1 when R=0.1','y2 when R=0.5','y3 when R=1','y4 when R=2','y5 when R=10')
% xlabel('Simulation time [s]')
% ylabel('y [m]')
% title('Lateral position')
% 
% 
% 
% figure()
% plot(w1,'--')
% hold on
% plot(w2,':')
% hold on
% plot(w3,'-.')
% hold on
% plot(w4,'-')
% hold on
% plot(w5,'--')
% legend('y1 when R=0.1','y2 when R=0.5','y3 when R=1','y4 when R=2','y5 when R=10')
% xlabel('Simulation time [s]')
% ylabel('delta [rad]')
% title('Steer Wheel Angle')
% 
